blank_issues_enabled: false
contact_links:
    - name: Ask a Support Question
      url: https://github.com/hsrvms/binance-bot/discussions
      about: Please ask general questions and seek configuration help in GitHub Discussions.
