"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MarketTick(_message.Message):
    """Injected by Go Ingestion / Replayer"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    EVENT_TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    price: _builtins.float
    volume: _builtins.float
    event_timestamp_ms: _builtins.int
    """Absolute source of truth for time"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        price: _builtins.float = ...,
        volume: _builtins.float = ...,
        event_timestamp_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_timestamp_ms", b"event_timestamp_ms", "price", b"price", "symbol", b"symbol", "volume", b"volume"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MarketTick: _TypeAlias = MarketTick  # noqa: Y015

@_typing.final
class IntentSignal(_message.Message):
    """Emitted by Python Engine"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    TARGET_EXPOSURE_FIELD_NUMBER: _builtins.int
    STRATEGY_REASONING_FIELD_NUMBER: _builtins.int
    SIGNAL_TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    target_exposure: _builtins.float
    """The desired final balance (e.g., 1.0 BTC)"""
    strategy_reasoning: _builtins.str
    """Context for alerts"""
    signal_timestamp_ms: _builtins.int
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        target_exposure: _builtins.float = ...,
        strategy_reasoning: _builtins.str = ...,
        signal_timestamp_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["signal_timestamp_ms", b"signal_timestamp_ms", "strategy_reasoning", b"strategy_reasoning", "symbol", b"symbol", "target_exposure", b"target_exposure"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___IntentSignal: _TypeAlias = IntentSignal  # noqa: Y015

@_typing.final
class PortfolioState(_message.Message):
    """Emitted by Go OMS on Startup Request"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class BalancesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.float
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.float = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    BALANCES_FIELD_NUMBER: _builtins.int
    STATE_TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    state_timestamp_ms: _builtins.int
    @_builtins.property
    def balances(self) -> _containers.ScalarMap[_builtins.str, _builtins.float]: ...
    def __init__(
        self,
        *,
        balances: _abc.Mapping[_builtins.str, _builtins.float] | None = ...,
        state_timestamp_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["balances", b"balances", "state_timestamp_ms", b"state_timestamp_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PortfolioState: _TypeAlias = PortfolioState  # noqa: Y015
