// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: trading/events.proto

package trading

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Injected by Go Ingestion / Replayer
type MarketTick struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbol           string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price            float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Volume           float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	EventTimestampMs int64                  `protobuf:"varint,4,opt,name=event_timestamp_ms,json=eventTimestampMs,proto3" json:"event_timestamp_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MarketTick) Reset() {
	*x = MarketTick{}
	mi := &file_trading_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketTick) ProtoMessage() {}

func (x *MarketTick) ProtoReflect() protoreflect.Message {
	mi := &file_trading_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketTick.ProtoReflect.Descriptor instead.
func (*MarketTick) Descriptor() ([]byte, []int) {
	return file_trading_events_proto_rawDescGZIP(), []int{0}
}

func (x *MarketTick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketTick) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketTick) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MarketTick) GetEventTimestampMs() int64 {
	if x != nil {
		return x.EventTimestampMs
	}
	return 0
}

// Emitted by Python Engine
type IntentSignal struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Symbol            string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TargetExposure    float64                `protobuf:"fixed64,2,opt,name=target_exposure,json=targetExposure,proto3" json:"target_exposure,omitempty"`
	StrategyReasoning string                 `protobuf:"bytes,3,opt,name=strategy_reasoning,json=strategyReasoning,proto3" json:"strategy_reasoning,omitempty"`
	SignalTimestampMs int64                  `protobuf:"varint,4,opt,name=signal_timestamp_ms,json=signalTimestampMs,proto3" json:"signal_timestamp_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IntentSignal) Reset() {
	*x = IntentSignal{}
	mi := &file_trading_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentSignal) ProtoMessage() {}

func (x *IntentSignal) ProtoReflect() protoreflect.Message {
	mi := &file_trading_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentSignal.ProtoReflect.Descriptor instead.
func (*IntentSignal) Descriptor() ([]byte, []int) {
	return file_trading_events_proto_rawDescGZIP(), []int{1}
}

func (x *IntentSignal) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *IntentSignal) GetTargetExposure() float64 {
	if x != nil {
		return x.TargetExposure
	}
	return 0
}

func (x *IntentSignal) GetStrategyReasoning() string {
	if x != nil {
		return x.StrategyReasoning
	}
	return ""
}

func (x *IntentSignal) GetSignalTimestampMs() int64 {
	if x != nil {
		return x.SignalTimestampMs
	}
	return 0
}

// Emitted by Go OMS on Startup Request
type PortfolioState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Balances         map[string]float64     `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StateTimestampMs int64                  `protobuf:"varint,2,opt,name=state_timestamp_ms,json=stateTimestampMs,proto3" json:"state_timestamp_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PortfolioState) Reset() {
	*x = PortfolioState{}
	mi := &file_trading_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioState) ProtoMessage() {}

func (x *PortfolioState) ProtoReflect() protoreflect.Message {
	mi := &file_trading_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioState.ProtoReflect.Descriptor instead.
func (*PortfolioState) Descriptor() ([]byte, []int) {
	return file_trading_events_proto_rawDescGZIP(), []int{2}
}

func (x *PortfolioState) GetBalances() map[string]float64 {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *PortfolioState) GetStateTimestampMs() int64 {
	if x != nil {
		return x.StateTimestampMs
	}
	return 0
}

var File_trading_events_proto protoreflect.FileDescriptor

const file_trading_events_proto_rawDesc = "" +
	"\n" +
	"\x14trading/events.proto\x12\atrading\"\x80\x01\n" +
	"\n" +
	"MarketTick\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\x12,\n" +
	"\x12event_timestamp_ms\x18\x04 \x01(\x03R\x10eventTimestampMs\"\xae\x01\n" +
	"\fIntentSignal\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12'\n" +
	"\x0ftarget_exposure\x18\x02 \x01(\x01R\x0etargetExposure\x12-\n" +
	"\x12strategy_reasoning\x18\x03 \x01(\tR\x11strategyReasoning\x12.\n" +
	"\x13signal_timestamp_ms\x18\x04 \x01(\x03R\x11signalTimestampMs\"\xbe\x01\n" +
	"\x0ePortfolioState\x12A\n" +
	"\bbalances\x18\x01 \x03(\v2%.trading.PortfolioState.BalancesEntryR\bbalances\x12,\n" +
	"\x12state_timestamp_ms\x18\x02 \x01(\x03R\x10stateTimestampMs\x1a;\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B;Z9github.com/hsrvms/binance-bot2/go-oms/internal/pb/tradingb\x06proto3"

var (
	file_trading_events_proto_rawDescOnce sync.Once
	file_trading_events_proto_rawDescData []byte
)

func file_trading_events_proto_rawDescGZIP() []byte {
	file_trading_events_proto_rawDescOnce.Do(func() {
		file_trading_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_events_proto_rawDesc), len(file_trading_events_proto_rawDesc)))
	})
	return file_trading_events_proto_rawDescData
}

var file_trading_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trading_events_proto_goTypes = []any{
	(*MarketTick)(nil),     // 0: trading.MarketTick
	(*IntentSignal)(nil),   // 1: trading.IntentSignal
	(*PortfolioState)(nil), // 2: trading.PortfolioState
	nil,                    // 3: trading.PortfolioState.BalancesEntry
}
var file_trading_events_proto_depIdxs = []int32{
	3, // 0: trading.PortfolioState.balances:type_name -> trading.PortfolioState.BalancesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trading_events_proto_init() }
func file_trading_events_proto_init() {
	if File_trading_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_events_proto_rawDesc), len(file_trading_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trading_events_proto_goTypes,
		DependencyIndexes: file_trading_events_proto_depIdxs,
		MessageInfos:      file_trading_events_proto_msgTypes,
	}.Build()
	File_trading_events_proto = out.File
	file_trading_events_proto_goTypes = nil
	file_trading_events_proto_depIdxs = nil
}
